build musl binaries for vscode extension
Summary:
This diff uses cross to build musl binaries for x64 linux/alpine builds of the vscode extension. This will close [163](https://github.com/facebook/pyrefly/issues/163).

I use cross because I had some headaches trying to manually install `musl-tools` following [this](https://github.com/rust-lang/backtrace-rs/issues/34) with no luck. cross fixes it for x64.

For context, ruff releases musl builds for binaries but [only use it in the vscode extension for alpine, not linux](https://github.com/astral-sh/ruff-vscode/blob/main/.github/workflows/release.yaml#L76C29-L76C36).

We do not do it for arm builds because I cannot get it to work:
`aarch64-unknown-linux-musl` target [fails](https://github.com/kinto0/pyrefly/actions/runs/15331467203/job/43139049844) with:
```
  include/jemalloc/internal/atomic.h:22:4: error: #error "Don't have atomics implemented on this platform."
```
this is from the implementation of jemalloc [here](https://github.com/jemalloc/jemalloc/blob/edaab8b3ad752a845019985062689551cd6315c1/include/jemalloc/internal/atomic.h#L22). chatgpt says we need `CFLAGS="-latomic"` in the compilation but I can't figure out how to do that. something like adding `ENV RUSTFLAGS="-C link-arg=-latomic"` [here](https://github.com/cross-rs/cross/blob/main/docker/Dockerfile.aarch64-unknown-linux-musl), but that's way over my head and i'm not sure how to test it.

I tried using arm-unknown-linux-musleabihf [here](https://github.com/kinto0/pyrefly/actions/runs/15331467203/job/43139049838) for armhf, but that fails with
```
  error occurred in cc-rs: failed to find tool "arm-linux-musleabi-gcc": No such file or directory (os error 2)
```
it seems less supported. maybe `aarch64-unknown-linux-musl` will work if I got it to, but I didn't.

If older glibc is needed, it might be easier to cross compile these to gnu arm builds [similar to ruff](https://github.com/astral-sh/ruff-vscode/blob/main/.github/workflows/release.yaml#L59) instead of musl.

Reviewed By: SamChou19815

Differential Revision: D75625464

fbshipit-source-id: 26556b35165635a8621d9184362684bd4e3a1b97