Move getting started out of fb to unbreak link in python-typing-5-minutes
Summary:
OSS website [builds are broken](https://github.com/facebook/pyrefly/actions/runs/14627020498/job/41040901051) with the following error:

```
Error:  Error: Unable to build website for locale en.
    at tryToBuildLocale (/home/runner/work/pyrefly/pyrefly/website/node_modules/docusaurus/core/lib/commands/build/build.js:78:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[INFO] Docusaurus version: 3.7.0
Node version: v20.19.0
    at async /home/runner/work/pyrefly/pyrefly/website/node_modules/docusaurus/core/lib/commands/build/build.js:34:9
    ... 4 lines matching cause stack trace ...
    at async file:///home/runner/work/pyrefly/pyrefly/website/node_modules/docusaurus/core/bin/docusaurus.mjs:44:3 {
  [cause]: Error: Docusaurus found broken links!

  Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
  Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

  Exhaustive list of all broken links found:
  - Broken link on source page path = /en/docs/python-typing-5-minutes/:
     -> linking to ../fb/getting-started/ (resolved as: /en/docs/fb/getting-started/)
```

This diff fixes the problem by removing the link for now.

Reviewed By: dluo

Differential Revision: D73535386

fbshipit-source-id: e6fbf0dd57145346fdde062f90f2544f59cfd5cd